name: Cocotb and Pytest Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cocotb cocotb-test pytest

      # Install Icarus Verilog
      - name: Install Icarus Verilog
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog

      # Run the test suite
      - name: Run Cocotb Tests
        run: |
          pytest path/to/your/tests

      # Display results
      - name: Display Test Results
        if: always()
        run: |
          cat path/to/your/tests/test_output.log || echo "No log file found"
